// Code generated by "stringer -type=Status -output=status_string.go"; DO NOT EDIT.

package backend

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Stale-0]
	_ = x[Alive-1]
	_ = x[Dead-2]
}

const _Status_name = "StaleAliveDead"

var _Status_index = [...]uint8{0, 5, 10, 14}

func (i Status) String() string {
	if i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
